USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE EDW;

-- Create New Schema
CREATE OR REPLACE SCHEMA EDW.CICD_SPIKE_JB
COMMENT = 'Created for CICD Spike. Testing multi-schema migrations.';

-- Grant Creator Role access usage on the schema
USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT ADD SEARCH OPTIMIZATION ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE EXTERNAL TABLE ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE FILE FORMAT ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE FUNCTION ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE MASKING POLICY ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE MATERIALIZED VIEW ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE PIPE ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE PROCEDURE ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE ROW ACCESS POLICY ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE SEQUENCE ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE SESSION POLICY ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE STAGE ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE STREAM ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE TABLE ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE TAG ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE TASK ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE TEMPORARY TABLE ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT CREATE VIEW ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT MODIFY ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";
GRANT MONITOR ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";

-- Create Table in New Schema
USE ROLE "DAA.Creator.SBX";
USE SCHEMA EDW.CICD_SPIKE_JB;

-- Create Table 1 in the Same Schema
CREATE OR REPLACE TABLE EDW.CICD_SPIKE_JB.TEST_TABLE_JB
(
	TABLE_KY VARCHAR(16777216),
    TABLE_DESC VARCHAR(16777216)
);

-- Create Table 2 in Another Schema
CREATE OR REPLACE TABLE EDW.CICD_SPIKE.TEST_TABLES_JB2
(
	TABLE_KY VARCHAR(16777216),
    TABLE_DESC VARCHAR(16777216)
);