USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE EDW;

-- Create New Schema
CREATE SCHEMA EDW.CICD_SPIKE_JB
WITH MANAGED ACCESS
COMMENT = 'Created for CICD Spike. Testing multi-schema migrations.';

-- Grant Creator Role access usage on the schema
USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA EDW.CICD_SPIKE_JB TO ROLE "DAA.Creator.SBX";

-- Create Table in New Schema
USE ROLE "DAA.Creator.SBX";
USE SCHEMA EDW.CICD_SPIKE_JB;

-- Create Table 1 in the Same Schema
CREATE OR REPLACE TABLE EDW.CICD_SPIKE_JB.TEST_TABLE_JB
(
	TABLE_KY VARCHAR(16777216),
    TABLE_DESC VARCHAR(16777216)
);

-- Create Table 2 in Another Schema
CREATE OR REPLACE TABLE EDW.CICD_SPIKE.TEST_TABLES_JB
(
	TABLE_KY VARCHAR(16777216),
    TABLE_DESC VARCHAR(16777216)
);