# Create Yaml File for Schema Change
name: SchemaChange

on: [push]
#  push:
#    branches: [ feature/test-functionality ]
#  workflow_dispatch:  

#setting up needed variables
env: 
 SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
 SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
 SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
 SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
 SNOWFLAKE_WH: ${{ secrets.SNOWFLAKE_WH }}
 SNOWFLAKE_DB: ${{ secrets.SNOWFLAKE_DB }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
      - name: Test with pytest
        run: |
          pytest
      - name: Test run
        run: |
          schemachange -f./schemachange/snowflake_objects -a     $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WH -c $SNOWFLAKE_DB.CICD_SPIKE.CHANGE_HISTORY 

          