name: Python tests - JB

on: 
  push:
    branches: [ master ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
      - name: Test with pytest
        run: |
          pytest
      - name: Test run
        run: |
          schemachange --help